all:
  hosts:
    ssh.vaguelyrudeplacesmap.com:
      compose_project: garygaledotcom
      site_fqdn: www.garygale.com
      site_bare: garygale.com
  vars:
    ansible_user: ubuntu
    deploy_root: /var/www
    deploy_user: ubuntu
    deploy_group: ubuntu
    traefik_network: vicchi-backend
